services:
  - type: static
    name: DEFI-Admin-front-end
    env: static
    plan: free
    buildCommand: npm install && npm run build
    publishPath: dist
    routes:
      - src: /.*
        dest: /index.html
